packages:
  - packages/*
  - plugins/*
  - docs
  - build

catalog:
  vite: ^7.3.1
  vitepress: ^1.6.4
  sass: ^1.99.0
  js-yaml: ^4.1.1
  picocolors: ^1.1.1
  tinyglobby: ^0.2.15
  gray-matter: ^4.0.3
  markdown-it-container: ^4.0.0
  "@iconify/vue": ^4.3.0
  "@types/js-yaml": ^4.0.9
  "@types/markdown-it": ^14.1.2
  "@types/markdown-it-container": ^4.0.0
  vitepress-plugin-auto-frontmatter: ^1.0.13
  vitepress-plugin-catalogue: ^1.1.2
  vitepress-plugin-doc-analysis: ^1.0.13
  vitepress-plugin-file-content-loader: ^1.0.13
  vitepress-plugin-md-h1: ^1.0.11
  vitepress-plugin-permalink: ^1.2.1
  vitepress-plugin-sidebar-resolve: ^1.2.3

catalogs:
  vue:
    vue: ^3.5.32
    "@vue/compiler-dom": ^3.5.32
    # "@vue/compiler-core": ^3.5.32
    # "@vue/reactivity": ^3.5.32
    # "@vue/runtime-core": ^3.5.32
    # "@vue/runtime-dom": ^3.5.32

onlyBuiltDependencies:
  - esbuild
  - '@parcel/watcher'
